@baseTheme=dark
@background=#005d74
@foreground=#FFFFFF
@accentColor=lighten ( @background , 50% , relative )
@selectionInactiveBackground=lighten (@background , 10% , relative )
# --- Global Colors ---
#app
@baseArc=30
App.arc=@baseArc
App.mainBackground=#1B7F94
App.mainTabbedPaneBackground=lighten ($App.mainBackground , 10% , relative )
App.baseBackground=@background
App.borderColor=#AABCF214
App.hoverBackground=$Button.hoverBackground
App.accent.color=@accentColor
App.success.color=#238636
App.warning.color=#d29922
App.danger.color=#f85149
# ????????? ? ???
Islands.accent=#00B478
# --- UI Defaults ---
Component.arc=20
Component.focusWidth=1
Component.innerFocusWidth=0
TextComponent.arc=20
@componentMargin=7,7,7,7
Button.margin=7,7,7,7
# --- Buttons ---
Button.arc=20
# --- ScrollPane ---
ScrollPane.arc = 20
ScrollPane.Table.arc=20
ScrollPane.List.arc=20
ScrollPane.Tree.arc=20
ScrollPane.TextComponent.arc=20
# --- TabbedPane ---
TabbedPane.tabHeight=50
TabbedPane.selectedBackground=@accentColor
TabbedPane.tabSelectionHeight=0
# --- Table ---
TableHeader.height=40
#TableHeader.background=@colorBg3
Table.showHorizontalLines=true
Table.showVerticalLines=true
Table.rowHeight=35
Table.background=@background
Table.intercellSpacing=1,1
# --- TextField ---
TextField.arc=10














