baseTheme=light
@background=#FFFFFF
@foreground=#24292F
@accentColor=#a8cbfe
@selectionInactiveBackground=darken ( @background , 5% , derived )
#---GlobalColors---
#app
@Arc=20
App.mainBackground=#ECEFF3
App.mainTabbedPaneBackground=lighten ($App.mainBackground , 2% , relative )
App.baseBackground=@background
App.borderColor=#AABCF214
App.hoverBackground=$Button.hoverBackground
App.accent.color=#58a6ff
App.success.color=#238636
App.warning.color=#d29922
App.danger.color=#f85149
#---UIDefaults---
Component.arc=20
Component.focusWidth=1
Component.innerFocusWidth=0
TextComponent.arc=20
@componentMargin=7,7,7,7
Button.margin=7,7,7,7
#---Buttons---
Button.arc=20
#---ScrollPane---
ScrollPane.Table.arc=20
ScrollPane.List.arc=20
ScrollPane.Tree.arc=20
ScrollPane.TextComponent.arc=20
#---TabbedPane---
TabbedPane.tabHeight=60
#TabbedPane.background=@colorBg2
TabbedPane.selectedBackground=@accentColor
#---Table---
TableHeader.height=40
TableHeader.background=darken ( @background , 10% , derived )
Table.showHorizontalLines=true
Table.showVerticalLines=true
Table.rowHeight=35
#Table.cellMargins = 2,2,2,2
Table.intercellSpacing = 1
Table.background=@background
Table.selectionForeground=@foreground
#---TextField---
TextField.arc=10




