app.name=dillon-admin-pro-swing
app.version=1.0.0

app.server.master.ip=127.0.0.1
app.server.slave.ip=127.0.0.1
app.server.port=48080
app.server.basePath=admin-api
app.server.scheme=http

# 自动更新配置
app.update.enabled=true
# 不配置时默认拼接:
# ${app.server.scheme}://${app.server.master.ip}:${app.server.port}/${app.server.basePath}/infra/client/update/swing/latest
app.update.metadata.url=
app.update.connect.timeout.ms=5000
app.update.read.timeout.ms=10000

# websocket 配置（支持主备）
app.websocket.enable=true
app.websocket.path=/infra/ws
app.websocket.master.url=ws://127.0.0.1:48080/infra/ws
app.websocket.slave.url=ws://127.0.0.1:48080/infra/ws
app.websocket.reconnect.delay.ms=5000
